// <auto-generated />
namespace Marketplace.Infrastructure.SecurityContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class InitialSecurityContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialSecurityContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201408281452112_InitialSecurityContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
