// <auto-generated />
namespace Marketplace.Infrastructure.SecurityContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RemovedVersioningAndAuditFromValueObjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RemovedVersioningAndAuditFromValueObjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201408291029062_RemovedVersioningAndAuditFromValueObjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
